### ISSUE TITLE
Unexpected error during export! See console for traceback.

### ISSUE THREAD

**Issue by zurgeg** [kergalym/YABEE#15]
When trying to export my file to .egg it shows this:
```
Unexpected error during export! See console for traceback.

```
There used to be a warning that said to select Mesh or Animation, but that warning went.
Any thoughts on how to fix this?
Thanks in Advance

**Comment by zurgeg** [comment]
Downloaded the `master` branch and it got past exporting then when i load it into pandas3d it says:
```
Traceback (most recent call last):
  File "C:\Users\zurgE\OneDrive\Documents\Blender Projects\python_3d.py", line 37, in <module>
    app = App()
  File "C:\Users\zurgE\OneDrive\Documents\Blender Projects\python_3d.py", line 22, in __init__
    self.pandaActor.loop('walk')
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\actor\Actor.py", line 1554, in loop
    for control in self.getAnimControls(animName, partName):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\actor\Actor.py", line 1848, in getAnimControls
    allowAsyncBind = allowAsyncBind)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\actor\Actor.py", line 2352, in __bindAnimToPart
    bundle = self.__commonBundleHandles[subpartDef.truePartName].getBundle()
KeyError: 'modelRoot'
```

**Comment by TurBoss** [comment]
I had this issue I think that selecting all the parts befor exporting does the trick

**Comment by kergalym** [comment]
Yes, you have two ways to do export: 
  1. Select all meshes of the character except armature, or
  2. Select all meshes of the character including armature

**Comment by jamesalbert** [comment]
@kergalym I'm getting the original error this issue mentions, any advice?

Stacktrace upon export:
```
bpy.context.space_data.recent_folders_active = 0
bpy.ops.scene.new(type='FULL_COPY')
bpy.ops.scene.delete()
Unexpected error during export! See console for traceback.
```

I've tried both the devel and master branches (which at this time are the same) just in case, same error on both. An .egg file gets created, but I don't see anything when I load it in panda.

OS: Windows 10 Pro
Blender: 2.82a
Attached: a zip of the blend file, egg file that does get exported but reports an error, gltf file that gets successfully exported and previewed using [https://gltf-viewer.donmccurdy.com/](https://gltf-viewer.donmccurdy.com/)

[demo.zip](https://github.com/kergalym/YABEE/files/4737909/demo.zip)
