### ISSUE TITLE
Nurb curves export not working

### ISSUE THREAD

**Issue by totex** [kergalym/YABEE#20]
Hello Kergalym,
After trying to export Nurb curves (for use as Motion paths in Panda3D) it always fails.

Here are a part of the error:
**TypeError: Element-wise multiplication: not supported between 'Matrix' and 'Vector'**
It also prints: 
**ID user decrement error: OBNurbCurve.001 (from '[Main]'): 0 <= 0**

I also tried with the old Yabee exporter in blender 2.79, that works perfectly.

**Comment by kergalym** [comment]
Fixed by [99c43b3](url=https://github.com/kergalym/YABEE/commit/99c43b37efc8b9e2d06707b4752cc528ab993fff)
