### ISSUE TITLE
Amazing job

### ISSUE THREAD

**Issue by Oneil974** [kergalym/YABEE#29]
Hi,

Sorry for creating an issue, but it's just for telling I was testing about few day your plugin but was not working.
So thank for your 15.0 update, it's just now work perfectly. 

Thanks

**Comment by kergalym** [comment]
YABEE code isn't clean written, since it was codestyle which the author of original YABEE preferred to use.
 Also, the code may contain more bugs, so we need more issues to make our exporter better :)
